### ISSUE TITLE
examples with pics

### ISSUE THREAD

**Issue by ashrafalzyoud** [apsmir/custom_field_sql#14]
your plugin so nice
but we need more example with pics to know more about this plugin
and im try to install it in redmine 5.0.2 ruby 3.1.2

```
redmine@redmine:~/5.0.2$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: cannot load such file -- custom_field_sql/custom_fields/formats/sql
/home/redmine/5.0.2/plugins/custom_field_sql/init.rb:2:in `block in <top (required)>'
/home/redmine/5.0.2/lib/redmine/plugin.rb:96:in `instance_eval'
/home/redmine/5.0.2/lib/redmine/plugin.rb:96:in `register'
/home/redmine/5.0.2/plugins/custom_field_sql/init.rb:1:in `<top (required)>'
/home/redmine/5.0.2/lib/redmine/plugin_loader.rb:31:in `load'
/home/redmine/5.0.2/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/home/redmine/5.0.2/lib/redmine/plugin_loader.rb:108:in `each'
/home/redmine/5.0.2/lib/redmine/plugin_loader.rb:108:in `block in load'
/home/redmine/5.0.2/config/environment.rb:16:in `<top (required)>'
/home/redmine/.rbenv/versions/3.1.2/bin/bundle:25:in `load'
/home/redmine/.rbenv/versions/3.1.2/bin/bundle:25:in `<main>'
Tasks: TOP => redmine:plugins:migrate => envir
```onment
(See full trace by running task with --trace)

**Comment by ashrafalzyoud** [comment]
@apsmir any update to redmine 5

**Comment by apsmir** [comment]
fixed with commit for redmine 5.x
